services:
  flink-jobmanager:
    image: flink:1.20.3-java17
    container_name: local-flink-jobmanager
    hostname: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - flink_checkpoints:/opt/flink/checkpoints
      - flink_savepoints:/opt/flink/savepoints
      - ./conf/config.yaml:/opt/flink/conf/config.yaml:ro
      - ../../flink/build/libs:/opt/flink/usrlib:ro
    networks:
      - default
      - kafka_network
      - clickhouse_network

  flink-taskmanager:
    image: flink:1.20.3-java17
    container_name: local-flink-taskmanager
    hostname: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - flink_checkpoints:/opt/flink/checkpoints
      - flink_savepoints:/opt/flink/savepoints
      - ./conf/config.yaml:/opt/flink/conf/config.yaml:ro
      - ../../flink/build/libs:/opt/flink/usrlib:ro
    networks:
      - default
      - kafka_network
      - clickhouse_network

networks:
  kafka_network:
    external: true
    name: kafka_default
  clickhouse_network:
    external: true
    name: clickhouse_default

volumes:
  flink_checkpoints:
  flink_savepoints: