package com.example.demo.entity

import jakarta.persistence.*
import java.time.LocalDateTime

@Entity
@Table(name = "order_transactions")
data class OrderTransaction(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val orderId: String,       // UUID generated by Gateway

    @Column(nullable = false)
    val accountId: String,     // Anonymous UUID from Browser

    @Column(nullable = false)
    val symbol: String,

    @Column(nullable = false)
    val side: String,          // BUY or SELL

    @Column(nullable = false)
    val quantity: Int,

    @Column(nullable = false)
    val price: Long,           // in cents

    @Column(nullable = false)
    var status: String,        // NEW, PARTIALLY_FILLED, FILLED, REJECTED

    @Column(nullable = false)
    var filledQuantity: Int = 0,

    @Column(nullable = false)
    val createdAt: LocalDateTime = LocalDateTime.now(),

    @Column(nullable = false)
    var updatedAt: LocalDateTime = LocalDateTime.now()
) {
    // Required by Hibernate
    protected constructor() : this(
        orderId = "",
        accountId = "",
        symbol = "",
        side = "",
        quantity = 0,
        price = 0,
        status = "NEW"
    )
}
