services:
  grafana:
    image: grafana/grafana:latest
    container_name: local-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    networks:
      - clickhouse_network

networks:
  clickhouse_network:
    external: true
    name: clickhouse_default

volumes:
  grafana_data:
